@localHost1=http://localhost:4000
@localHost2=http://localhost:4000

POST {{localHost1}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  register(email: "vapehe1245@iopmail.com", password: "mypassword", username:"obiwewe"){
    path
    message
  }
}
###

POST {{localHost1}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(email: "vapehe1245@iopmail.com", password: "Newpass12"){
    path
    message
  }
}

###

POST {{localHost1}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  me {
    username
    email
  }
}

###
POST {{localHost1}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  logout
}
###

POST {{localHost1}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  forgotPassword(email:"vapehe1245@iopmail.com"){
    path
    message
  }
}
###

POST {{localHost1}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  changePassword(newPassword:"Newpass12", key:"6a0e4160-6f52-4601-82db-ca3bae88441e"){
    path
    message
  }
}